import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { NextIntlClientProvider } from 'next-intl';
import { notFound } from 'next/navigation';
import { cookies } from 'next/headers';

const inter = Inter({ subsets: ['latin'] });

export function generateStaticParams() {
  return [{locale: 'en'}, {locale: 'nl'}];
}

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
  params
}: {
  children: React.ReactNode,
  params: any
}) {
  const { locale } = params;
  const cookieStore = cookies();
  const token = cookieStore.get('token');

  let messages;
  try {
    console.log("locale", params);
    messages = (await import(`../../messages/${locale}.json`)).default;
  } catch (error) {
    console.log("++", error);
    notFound();
  }
  console.log("locale", locale);
  return (
    <html lang={locale}>
      <body className={inter.className}>
        <NextIntlClientProvider locale={locale} messages={messages || {}}>
            {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
